## The Tensorflow Trials

For much of the past week, you've been using tensors with your Deep Learning models. Over the course of today's challenges, you'll be manipulating tensors extensively and working with some unconventional model architectures. 


In this warm up, you'll be introduced to some new methods. 

All the methods here are going to make tackling challenges later in the day 100x easier, so if you do get stuck later on, make sure you come back here to see how you achieved the right answers. 

In [1]:
import tensorflow as tf


2023-11-17 10:27:57.384998: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/Users/tanushrinayak/.pyenv/versions/3.10.6/envs/lewagon/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


A) Use `tf.ones` to create a tensor `a` filled with ones of shape (3,3).

In [5]:
# Use tf.ones to create a 3x3 tensor full of ones.

a = tf.ones([3, 3])

print(a)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


B) Use tf.expand_dims to make `a` an object of shape (1,3,3) called `b`.

In [9]:
# Use tf.expand_dims to add a dimension to your tensor and
# store it in b.

b = tf.expand_dims(a, 0)

print(b)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 3, 3), dtype=float32)


C) Create a tensor `c` filled with zeroes of size (9,1)

In [7]:
# Create a tensor c with zeroes of size (9,1)
c = tf.zeros([9, 1])

print(c)


tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(9, 1), dtype=float32)


D) Reshape `c` to be of shape (1, 3, 3). Name it `d`.

In [8]:
# Reshape c to be of shape (1,3,3)

d = tf.reshape(c, [1, 3, 3])

print(d)


tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 3, 3), dtype=float32)


E) Use `tf.matmul` to matrix multiply `b` and `d` with each other and now assign the tensor to `e`. 

In [10]:
# Multiply b and d together to get e
e = tf.matmul(b, d)

print(e)


tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 3, 3), dtype=float32)


F) Below is a `numpy` array. Convert it to a tensor named `array_tensor`. Then use `tf.cast` to ensure it oof dtype `float` not `int`. Assign the result to `f`.

In [11]:
import numpy as np


In [12]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])


In [13]:
# Convert the numpy array into a tensor using tf.cast
f = tf.cast(array, tf.float32)

print(f)


tf.Tensor(
[[[1. 2. 3.]
  [1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]], shape=(1, 4, 3), dtype=float32)


G) Select the values in the __last column__ of `f` and save this to `g`. To be clear, `g` should have shape (4,) and contain the values `3,3,6,9`. 

In [45]:
# Take the last column of f and store it in g with shape (4,)

g = f[:,:,2]

# Reshape g to be of shape (4,)

g = tf.reshape(g, [4, ])

print(g)
print(g.shape)


tf.Tensor([3. 3. 6. 9.], shape=(4,), dtype=float32)
(4,)


H) Expand the dimensions of g so that it's of shape (4,1). Assign this to `h`.

In [15]:
# Reshape g into a shape (4,1)

h = tf.reshape(g, [4, 1])

print(h)


tf.Tensor(
[[3.]
 [3.]
 [6.]
 [9.]], shape=(4, 1), dtype=float32)


H) Multiply e with f, using `tf.matmul` with the optional `transpose_b` argument (`e` must come first in your positional arguments, then `f`). Assign this to `h`.

In [17]:
# Multiply e with f using tf.matmul with the optional
# argument transpose_b set to True.

h = tf.matmul(e, f, transpose_b=True)

print(h)


tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 3, 4), dtype=float32)


I) Create a `(10,10)` tensor filled with ones. Then use `tf.linaalg.band_part()` to mask out the upper triangle of the matrix (i.e. the upper triangle should all be 0s). Assign to `i`.

In [19]:
# Create a (10, 10) tensor of 1s and
# use tf.linalg.band_part() to mask out the upper triangle.

i = tf.ones([10, 10])

i = tf.linalg.band_part(i, -1, 0)

print(i)


tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


J) Take the `number_list` below and make it a tensor. Assign it to `j`.

In [20]:
number_list = [1,2,3,4,8]


In [21]:
# Make number_list into a tensor using tf.convert_to_tensor

j = tf.convert_to_tensor(number_list)

print(j)


tf.Tensor([1 2 3 4 8], shape=(5,), dtype=int32)


K) Use `tf.expand_dims` to make `j` into a tensor of shape (1,5). Assign to `k`.

In [22]:
# Use tf.expand_dims to make j into a tensor of shape (1,5)

k = tf.expand_dims(j, 0)

print(k)


tf.Tensor([[1 2 3 4 8]], shape=(1, 5), dtype=int32)


L) Use `tf.tile` to repeat `k` 50 times, with an eventual shape of `(50,5)`. Assign to `l`.

In [23]:
# Use tf.tile to repeat k 50 times

l = tf.tile(k, [50, 1])

print(l)


tf.Tensor(
[[1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]
 [1 2 3 4 8]], shape=(50, 5), dtype=int32)


M) Use a simple Boolean statement to create a tensor containing `True` and `False` values for where `l` does not equal 3. Assign to `m`

In [24]:
# Use a simple Boolean statement to create a tensor
# containing True and False values, where l is not equal to 3
m = l != 3

print(m)


tf.Tensor(
[[ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]

N) Divide every value in you variable `l` (read as "L") by 3. Assign to `n`.

In [25]:
# Divide every value in l by 3 and store it in n

n = tf.divide(l, 3)

print(n)


tf.Tensor(
[[0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0.33333333 0.66666667 1.         1.33333333 2.66666667]
 [0

O) Use `tf.concat()` to take the list of two tensors below of shape (5,5) and (5,5) each and turn them into a final tensor of shape (10,5). Assign to `o`. Think carefully about the concation axis.

In [26]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]


In [27]:
# Use tf.concat to concatenate tensor_list along the first dimension

o = tf.concat(tensor_list, axis=0)

print(o)


tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(10, 5), dtype=float32)


### Check your answers

In [46]:
from nbresult import ChallengeResult

result = ChallengeResult('tensors',
                            a = a,
                            b = b,
                            c = c,
                            d_shape = d.shape,
                            e = e,
                            f = f,
                            g = g,
                            h = h,
                            i = i,
                            j = j,
                            k = k,
                            l = l,
                            m = m,
                            n = n,
                            o_shape = o.shape
)

result.write()
print(result.check())



============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0 -- /Users/tanushrinayak/.pyenv/versions/3.10.6/envs/lewagon/bin/python3
cachedir: .pytest_cache
rootdir: /Users/tanushrinayak/code/tanushrin/06-Deep-Learning/05-Transformers/data-tensor-trials/tests
plugins: asyncio-0.19.0, typeguard-2.13.3, anyio-3.6.2
asyncio: mode=strict
collecting ... collected 15 items

test_tensors.py::TestTensors::test_a PASSED                              [  6%]
test_tensors.py::TestTensors::test_b PASSED                              [ 13%]
test_tensors.py::TestTensors::test_c PASSED                              [ 20%]
test_tensors.py::TestTensors::test_d_shape PASSED                        [ 26%]
test_tensors.py::TestTensors::test_e PASSED                              [ 33%]
test_tensors.py::TestTensors::test_f PASSED                              [ 40%]
test_tensors.py::TestTensors::test_g PASSED                        

### Great work 🔥

Now it's time to get stuck into some modelling!